sudo: required
services:
  - docker
before_install:
  - docker build -t desmonduz/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true desmonduz/docker-react npm run test
deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-241252774995"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_ACCESS_SECRET
language: generic